M48
; DRILL file KiCad 10.0.0 date 2026-07-02T13:10:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-02T13:10:22+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X122.728Y-43.735
X126.829Y-47.836
T2
X67.5Y-67.85
X68.8Y-21.9
X114.8Y-40.75
M30
